version: '3.8'

services:
  web:
    image: influencemapper-web:latest
    build:
      context: services/web
    ports:
        - "80:8000"
    volumes:
        - ./service/web/app:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    ports:
        - "6379:6379"
    restart: always


  core:
    image: influencemapper-core:latest
    build:
      context: services/core
    volumes:
        - ./service/core/app:/app
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379